import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";

const prod = process.argv[2] === "production";
const projectRoot = path.dirname(fileURLToPath(import.meta.url));
const safeImmediatePath = path.join(projectRoot, "src/shims/safeImmediate.js");
const safeSetImmediatePath = path.join(projectRoot, "src/shims/safeSetImmediate.js");

const HEAVY_DEPS = ["jszip", "mammoth", "@e965/xlsx", "word-extractor", "ppt-to-text"];

const reviewSafeSchedulerShims = {
  name: "review-safe-scheduler-shims",
  setup(build) {
    build.onResolve({ filter: /^immediate$/ }, () => ({ path: safeImmediatePath }));
    build.onResolve({ filter: /^setimmediate$/ }, () => ({ path: safeSetImmediatePath }));
  }
};

const depEntries = {
  "jszip": "src/loaders/jszipEntry.js",
  "mammoth": "src/loaders/mammothEntry.js",
  "xlsx": "src/loaders/xlsxEntry.js",
  "word-extractor": "src/loaders/wordExtractorEntry.js",
  "ppt-to-text": "src/loaders/pptToTextEntry.js",
};

async function buildDepBundles(outDir) {
  fs.mkdirSync(outDir, { recursive: true });
  for (const [name, entry] of Object.entries(depEntries)) {
    await esbuild.build({
      entryPoints: [entry],
      bundle: true,
      platform: "node",
      format: "cjs",
      target: "es2018",
      outfile: path.join(outDir, `${name}.js`),
      minify: prod,
      logLevel: "info",
    });
  }
}

const context = await esbuild.context({
  banner: { js: "/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */" },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron", "@codemirror/autocomplete", "@codemirror/collab", "@codemirror/commands", "@codemirror/language", "@codemirror/lint", "@codemirror/search", "@codemirror/state", "@codemirror/view", "@lezer/common", "@lezer/highlight", "@lezer/lr", ...builtins, ...HEAVY_DEPS],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [reviewSafeSchedulerShims]
});

if (prod) {
  await context.rebuild();
  await context.dispose();

  const buildDir = path.join(projectRoot, "build");
  const depsDir = path.join(buildDir, "deps");
  await buildDepBundles(depsDir);
  for (const file of ["main.js", "styles.css", "manifest.json"]) {
    fs.copyFileSync(path.join(projectRoot, file), path.join(buildDir, file));
  }
} else {
  const depsDir = path.join(projectRoot, "deps");
  await buildDepBundles(depsDir);
  // Rebuild dep bundles on every main build so dev changes to entry files are reflected.
  context.rebuild = (async () => {
    const originalRebuild = context.rebuild;
    return async () => {
      await buildDepBundles(depsDir);
      return originalRebuild.call(context);
    };
  })();
  await context.watch();
}
